# Generated by Django 4.2.13 on 2024-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKING_SYSTEM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20),
        ),
    ]
